[package]
name = "stash-compilation-maker"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.10", features = ["macros"] }
camino = "1.1.3"
console = "0.15.5"
dialoguer = "0.10.3"
directories = "4.0.1"
graphql_client = "0.12.0"
indicatif = "0.17.3"
lazy_static = "1.4.0"
rand = "0.8.5"
regex = "1.7.1"
reqwest = { version = "0.11.14", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
tokio = { version = "1.26.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
